// generated by gen_wx_fonts.py — aggregator. include this once (main.cpp).
#pragma once
#include <stdint.h>
#ifndef U8G2_FONT_SECTION
#define U8G2_FONT_SECTION(name)
#endif
#include "pop_temp.h"
#include "pop_clock.h"
#include "pop_mid.h"
#include "lsjp_xb30.h"
#include "lsjp_b24.h"
#include "lsjp_r20.h"
#include "lsjp_r13.h"
#include "lsjp_news.h"
